settings:
  APP_DISPLAY_NAME: ketal
  PRODUCTION_APP_NAME: ketal
  APP_GROUP_IDENTIFIER: group.io.ketal
  BASE_BUNDLE_IDENTIFIER: io.ketal.app
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 7J4U792NQT
